sudo: required
services:
  - docker

before_install:
  - docker build -t sudeeshbhaskaran/juzgodigital -f ./juzgodigital-frontend/Dockerfile.dev ./juzgodigital-frontend

script:
  - docker build -t sudeeshbhaskaran/juzgodigital-frontend ./juzgodigital-frontend
  - docker build -t sudeeshbhaskaran/juzgodigital-backend ./juzgodigital-backend
  - docker build -t sudeeshbhaskaran/juzgodigital-nginx ./juzgodigital-nginx

  - echo "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID"  --password-stdin

  - docker push sudeeshbhaskaran/juzgodigital-frontend
  - docker push sudeeshbhaskaran/juzgodigital-backend

  - docker push sudeeshbhaskaran/juzgodigital-nginx
